import sys


os.environ["OPP_TOP_CONFIG"] = "/var/www/openpassphrase/.opp/opp.cfg"
sys.path.insert(0, "/var/www/openpassphrase")
sys.path.insert(0, "/var/www/openpassphrase/venv/lib/python3.10/site-packages")


def execfile(filename):
    globals = dict( __file__ = filename )
    exec( open(filename).read(), globals )

activate_this = '/var/www/openpassphrase/venv/bin/activate_this.py'
execfile(activate_this)


from opp.flask import app as application
